// contract.js
// The BSCH hiring contract. /contract sends this text and snapshots it onto
// the case, so a client's agreement is always tied to the exact wording they
// saw. Edit the text here and push; bump VERSION whenever the terms change.

const VERSION = 'v1.0';

const TEXT = `**BSCH Hiring Agreement**
Beanz's Server Creating Helpers — Discord Server Build Agreement
Contract Version: ${VERSION}

This agreement is generated by the BSCH bot when a Project Lead sends it in a client's ticket. By confirming in Discord, the client agrees to the terms below, and the bot logs the contract version accepted along with the date and both parties' Discord IDs.

**1. Parties**
BSCH ("we," "us"), represented in this ticket by the assigned Project Lead builder and any additional builders added to the ticket roster.
The Client ("you"), the member who opened this ticket and owns or administers the Discord server being worked on.

**2. Scope of Work**
The scope is defined by the project info and any extra details you provided in this ticket. Any request outside that scope should be discussed and added to the ticket before work begins on it.

**3. Cost — Free of Charge**
BSCH provides this service free of charge. You are under no obligation to pay for this build. After the project is complete and you've left a rating/review, the bot may share an optional donation link. Donating is voluntary and has no effect on the work you receive.

**4. Server Access**
You will grant BSCH's assigned builder(s) admin access to your server so the build can happen live.
Access is to be used only for the agreed scope of work.
After the ticket is closed, the bot will remind you to revoke BSCH's admin access. Revoking access is your responsibility.

**5. Template Bank Consent**
If your build is unique, BSCH may want to save a copy to our internal template database for future reuse in other clients' projects. This only happens with your consent, which you give with the buttons below: accept with copying allowed, or accept without it. Your answer is recorded on the case and can be changed by telling your Lead before the build is finished.

**6. Roster & Team**
Your Project Lead may bring in other BSCH builders to help. Everyone working on your project is tracked on the ticket's roster, viewable by you or staff at any time on request.

**7. Timeline & Communication**
BSCH is a volunteer community — we do our best to move quickly, but we don't guarantee a fixed completion date. Your Lead will keep you updated in the ticket. If your Lead or the assigned builders go quiet for an extended period, contact staff and a senior staff member can reassign your ticket.

**8. Cancellation**
You may cancel at any point by telling your Lead in the ticket. If you cancel mid-build, the ticket closes without a paperwork or rating step.
If you become unreachable for an extended period, BSCH may flag the ticket inactive and archive it.
BSCH reserves the right to pause or reassign a project if a builder becomes unavailable — this will not cost you anything or restart the process from scratch where avoidable.

**9. Your Responsibilities**
Grant the access needed to complete the agreed scope.
Respond to requests for info in a reasonable time.
Treat BSCH builders with the same respect you'd expect in return.

**10. BSCH's Responsibilities**
Build to the scope agreed in this ticket.
Follow your creative direction within that scope.
Not make changes to your server outside the agreed work without asking first.

**11. Disputes**
Any disagreement between you and your Lead — or between builders on your project — that can't be resolved in the ticket gets escalated to BSCH senior staff for a final call.

**12. After Completion**
The bot will ask you for a rating/review.
Your Lead will file paperwork (photos, builders credited) for BSCH's internal records.
A summary of your build is logged in BSCH's records and can be pulled up later with !buildlogs if you ever come back for more work.

By confirming in this ticket, you acknowledge you've read and agree to the terms above.`;

// Discord embed descriptions cap at 4096 characters, so long contracts are
// sent as several embeds in one message. Split on blank lines so a section
// never gets cut in half.
function chunks(text = TEXT, size = 3800) {
  const out = [];
  let current = '';
  for (const block of text.split('\n\n')) {
    if (current && current.length + block.length + 2 > size) {
      out.push(current);
      current = '';
    }
    current += (current ? '\n\n' : '') + block;
  }
  if (current) out.push(current);
  return out;
}

module.exports = { VERSION, TEXT, chunks };
